# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-c6p_EUMIlvJxjuRZPMO6TOczfbJ4aJH
"""

import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 3, tight_layout = True)


#折れ線 axes[0,0]
y0 = [1, 2, -4, 2]
axes[0,0].plot(y0)

axes[0,0].set(xlim=(0, 3), xticks=np.arange(0, 4),
             ylim=(-5, 6), yticks=np.arange(-5, 6))

#SIN関数 axes[0,1]
x1 = np.linspace(0, 10, 100)
y1 = 2 + 2 * np.sin(2 * x1)

axes[0,1].plot(x1, y1, linewidth=2.0)
axes[0,1].set(xlim=(0, 10), xticks=np.arange(0, 11),
              ylim=(-1, 5), yticks=np.arange(-1, 6))

#ヒストグラム axes[0,2](平均が15, 標準偏差5の標準正規分布から2000個の乱数の生成する)
x3 = np.random .normal(15, 5, 2000)
# ヒストグラムをプロット axes[0,2].plot(hist(x3, bins=30))となると思ったが、以下でうまくいった。
axes[0,2].hist(x3, bins=30)


#散布図 axes[1,0]
np.random.seed(3)
x4 = 4 + np.random.normal(0, 2, 60)
y4 = 4 + np.random.normal(0, 2, len(x4))

#散布図をプロットする
axes[1,0].scatter(x4, y4)